stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/telco_customer_churn_data.csv
    outs:
      - data/processed/ingested_data.csv

  preprocessing:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/processed/ingested_data.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - models/scaler.pkl
      - models/feature_columns.json

  training:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    outs:
      - models/model.pkl

  evaluation:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/test.csv
      - models/model.pkl